### ISSUE TITLE
When I changed Missing to All and clicked Update I got the following error: This page did not call $PAGE->set_url(...).

### ISSUE THREAD

**Issue by jgramp** [andrewhancox/moodle-atto_translations#2]
When I changed Missing to All and clicked Update I got the following error:
![image](https://user-images.githubusercontent.com/8575694/167097507-0e8f3612-65ff-4ae3-9938-4d4f3a2cb14a.png)

**Comment by jgramp** [comment]
Actually it seems to happen as soon as you click the 'update' button, regardless of what is selected in the form, even if the filter options remain the same with Status = "missing"

**Comment by andrewhancox** [comment]
I couldn't reproduce the issue but have fixed the root cause.
