### ISSUE TITLE
Multiple hash span tags in quiz question options

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-atto_translations#3]
Every time a quiz question is updated/edited, additional span tags seem to get added, even if there already is a span tag.
Empty question options/feedback still have span tags added.

![image](https://user-images.githubusercontent.com/4531184/168202235-ed4ba332-e4c5-4748-bde2-ce68e91be22d.png)

**Comment by andrewhancox** [comment]
There was a bug that only showed up in this instance - not 100% sure why, I think there is something slightly out of the ordinary in how these editors are initialised...

**Comment by jgramp** [comment]
Is this resolved now Rajneel?
